// import './instance'
// import './lifestyle'
// import './data-binding'
// import './computed'
// import './derective'
// import './component/default'
// import './component/extend'
// import './component/vmodel'
import './component/feture'
